db:
  db_user: django_aws
  db_host: postgres-db.cdsm2gomilsw.eu-central-1.rds.amazonaws.com
  db_name: django_db
  db_password: 12345678q

app:
  replicas: 2
  image: 777484289756.dkr.ecr.eu-central-1.amazonaws.com/django-app:latest
  allowedHosts: "*"
  port: 8080

probes:
  readiness:
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10

# hpa
autoscaling:
  minReplicas: 2
  maxReplicas: 4

metrics:
  cpu:
    averageUtilization: 80
  memory:
    averageUtilization: 80

#service
service:
  port: 80        
  targetPort: 8080  
  type: NodePort

# ingress
ingress:
  name: my-ingress-lb 
  scheme: internet-facing
  targetType: instance
  loadBalancerName: my-ingress-lb
  listenPorts: '[{"HTTP": 80}, {"HTTPS": 443}]'
  certificateArn: arn:aws:acm:eu-central-1:777484289756:certificate/c71f219a-8e4e-4856-be72-68f1fe1e065e
  host: helm-chart.top-devops.com

alb:
  ingressClassName: alb  