apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DEBUG: "False"
  DATABASE_URL: "postgresql://user:db-password@db-host:5432/db-name"
  db-user: {{ .Values.db.user }}
  db-host: {{ .Values.db.host }}
  db-name: {{ .Values.db.name }}