apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          image: {{ .Values.app.image }}
          command: ["sh", "-c", "python3 manage.py migrate"]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_user
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_host
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):5432/$(DATABASE_NAME)
            - name: DJANGO_ALLOWED_HOSTS
              value: "{{ .Values.app.allowedHosts }}"
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.image }}
          command: ["gunicorn", "mysite.wsgi:application", "--bind", "0.0.0.0:{{ .Values.app.port }}"]
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_user
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_host
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):5432/$(DATABASE_NAME)
            - name: DJANGO_ALLOWED_HOSTS
              value: "{{ .Values.app.allowedHosts }}"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
